
APPLICATION_FRAMR_PRODUCT=applications/framr/framr
APPLICATION_FRAMR_OBJECTS=applications/framr/framr.o applications/framr/main.o

APPLICATION_EXECUTABLES+=$(APPLICATION_FRAMR_PRODUCT)
APPLICATION_OBJECTS+=$(APPLICATION_FRAMR_OBJECTS)

$(APPLICATION_FRAMR_PRODUCT): $(APPLICATION_FRAMR_OBJECTS) $(LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
